// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void key_up_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen(lv_event_t * e);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_week;
void ui_event_wifibutton(lv_event_t * e);
lv_obj_t * ui_wifibutton;
void ui_event_ImgButton2(lv_event_t * e);
lv_obj_t * ui_ImgButton2;
lv_obj_t * ui_city;
lv_obj_t * ui_tianqi;
lv_obj_t * ui_time;
lv_obj_t * ui_temper;
lv_obj_t * ui_date;


// SCREEN: ui_Charts
void ui_Charts_screen_init(void);
void ui_event_Charts(lv_event_t * e);
lv_obj_t * ui_Charts;
lv_obj_t * ui_Chart1;


// SCREEN: ui_Wifi
void ui_Wifi_screen_init(void);
void ui_event_Wifi(lv_event_t * e);
lv_obj_t * ui_Wifi;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
void ui_event_Dropdown1(lv_event_t * e);
lv_obj_t * ui_Dropdown1;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;
void ui_event_TextArea1(lv_event_t * e);
lv_obj_t * ui_TextArea1;


// SCREEN: ui_DataMenu
void ui_DataMenu_screen_init(void);
void ui_event_DataMenu(lv_event_t * e);
lv_obj_t * ui_DataMenu;
lv_obj_t * ui_WenduBar;
lv_obj_t * ui_HumiBar;
lv_obj_t * ui_WenduLab;
lv_obj_t * ui_HumiLab;
lv_obj_t * ui_Pt100Lab;
lv_obj_t * ui_Pt100Bar;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Image6;
lv_obj_t * ui_CoBar;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_CoLab;


// SCREEN: ui_Other
void ui_Other_screen_init(void);
void ui_event_Other(lv_event_t * e);
lv_obj_t * ui_Other;
lv_obj_t * ui_Label4;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Label5;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_wifi_[1] = {&ui_img_wifi_1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void key_up_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 140, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_MainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Charts, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Charts_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_DataMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_DataMenu_screen_init);
    }
}
void ui_event_wifibutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Wifi, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_Wifi_screen_init);
    }
}
void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Other, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0, &ui_Other_screen_init);
    }
}
void ui_event_Charts(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_Wifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0, &ui_MainScreen_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ScanAPEvent(e);
    }
}
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ConnetEvent(e);
    }
}
void ui_event_Dropdown1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        EnterEvent(e);
    }
}
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        key_up_Animation(ui_Keyboard1, 0);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_DataMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_Other(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        LightPwm(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui_Charts_screen_init();
    ui_Wifi_screen_init();
    ui_DataMenu_screen_init();
    ui_Other_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
    inti_event();
}
