// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void key_up_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen(lv_event_t * e);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_week;
void ui_event_wifibutton(lv_event_t * e);
extern lv_obj_t * ui_wifibutton;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_city;
extern lv_obj_t * ui_tianqi;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_temper;
extern lv_obj_t * ui_date;
// SCREEN: ui_Charts
void ui_Charts_screen_init(void);
void ui_event_Charts(lv_event_t * e);
extern lv_obj_t * ui_Charts;
extern lv_obj_t * ui_Chart1;
// SCREEN: ui_Wifi
void ui_Wifi_screen_init(void);
void ui_event_Wifi(lv_event_t * e);
extern lv_obj_t * ui_Wifi;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
void ui_event_Dropdown1(lv_event_t * e);
extern lv_obj_t * ui_Dropdown1;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
// SCREEN: ui_DataMenu
void ui_DataMenu_screen_init(void);
void ui_event_DataMenu(lv_event_t * e);
extern lv_obj_t * ui_DataMenu;
extern lv_obj_t * ui_WenduBar;
extern lv_obj_t * ui_HumiBar;
extern lv_obj_t * ui_WenduLab;
extern lv_obj_t * ui_HumiLab;
extern lv_obj_t * ui_Pt100Lab;
extern lv_obj_t * ui_Pt100Bar;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_CoBar;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_CoLab;
// SCREEN: ui_Other
void ui_Other_screen_init(void);
void ui_event_Other(lv_event_t * e);
extern lv_obj_t * ui_Other;
extern lv_obj_t * ui_Label4;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_wifi_1_png);    // assets/wifi_1.png
LV_IMG_DECLARE(ui_img_yituflow_png);    // assets/yituflow.png
LV_IMG_DECLARE(ui_img_temperature_png);    // assets/temperature.png
LV_IMG_DECLARE(ui_img_humidity_png);    // assets/humidity.png
LV_IMG_DECLARE(ui_img_wifi_ic_png);    // assets/wifi_ic.png



LV_FONT_DECLARE(ui_font_Black28);
LV_FONT_DECLARE(ui_font_bold24);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
