// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include <esp_err.h>
#include "ui.h"
#include "lvgl_helpers.h"

#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"
#define MAX_NETWORKS 5
#define DEFAULT_PASSWORD "123456789"
static const char *TAG = "WiFi_Scan";
static char wifiNetworks[MAX_NETWORKS][33];
static void updateDropdownMenu(lv_obj_t * dropdown) {
    lv_dropdown_clear_options(dropdown);
    for (int i = 0; i < MAX_NETWORKS; ++i) {
        if (strlen(wifiNetworks[i]) > 0) {
            lv_dropdown_add_option(dropdown, wifiNetworks[i], LV_DROPDOWN_POS_LAST);
        }
    }
}

void ScanAPEvent(lv_event_t * e)
{

}
static void wifi_connect(const char *ssid, const char *password) {
    wifi_config_t wifi_config = {
            .sta = {
                    .ssid = "",
                    .password = "",
            },
    };
    ESP_ERROR_CHECK(esp_wifi_disconnect());
    strncpy((char *)wifi_config.sta.ssid, ssid, sizeof(wifi_config.sta.ssid));
    strncpy((char *)wifi_config.sta.password, password, sizeof(wifi_config.sta.password));
    ESP_LOGI(TAG, "Connecting to %s...", ssid);
    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));
    ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA, &wifi_config));
    ESP_ERROR_CHECK(esp_wifi_connect());
}
void ConnetEvent(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_target(e);
    if(lv_obj_has_state(obj, LV_STATE_CHECKED)) {
        char ssid[33];
        char password[65];
        lv_dropdown_get_selected_str(ui_Dropdown1, ssid, sizeof(ssid));
        strcpy(password, lv_textarea_get_text(ui_TextArea1));
        ESP_LOGI(TAG, "Selected SSID: %s", ssid);
        ESP_LOGI(TAG, "Password: %s", password);
        wifi_connect(ssid, password);
    }
}
void EnterEvent(lv_event_t * e)
{
    lv_obj_t *keyboard = (lv_obj_t *)e->target;
    uint16_t btn = lv_keyboard_get_selected_btn(keyboard);
    if(btn==35||btn==39){
        lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);
    }
}
void LightPwm(lv_event_t * e)
{
    static char buf[8];
    lv_obj_t *slider = (lv_obj_t *)e->target;
    int brightness = lv_slider_get_value(slider);//获取滑动条值
    disp_backlight_set((disp_backlight_h *)pwm_light_handler,brightness);//设置PWM值
    sprintf(buf, "%d%%", brightness);
    lv_label_set_text(ui_Label5, buf);//值显示
}
void scanWiFiNetworks(void) {
    uint16_t number = MAX_NETWORKS;
    wifi_ap_record_t ap_info[MAX_NETWORKS];
    uint16_t ap_count = 0;
    memset(ap_info, 0, sizeof(ap_info));
    esp_wifi_scan_start(NULL, true);
    ESP_ERROR_CHECK(esp_wifi_scan_get_ap_records(&number, ap_info));
    ESP_ERROR_CHECK(esp_wifi_scan_get_ap_num(&ap_count));
    ESP_LOGI(TAG, "Total APs scanned = %u", ap_count);
    for (int i = 0; (i < MAX_NETWORKS) && (i < ap_count); i++) {
        snprintf(wifiNetworks[i], sizeof(wifiNetworks[i]), "%s", ap_info[i].ssid);
        ESP_LOGI(TAG, "SSID %d: %s", i, wifiNetworks[i]);
    }
    updateDropdownMenu(ui_Dropdown1);
}

void label_event_cb(lv_event_t* e)
{
    lv_obj_t* label = lv_event_get_target(e);
    lv_msg_t* m = lv_event_get_msg(e);

    const char* fmt = lv_msg_get_user_data(m);

    if (strstr(fmt, "%s") != NULL)
    {
        /* 字符串填入 */
        const char* v = lv_msg_get_payload(m);
        lv_label_set_text_fmt(label, fmt, v);
    }
    else
    {
        /* 数字填入 */
        const char* v = lv_msg_get_payload(m);
        lv_label_set_text_fmt(label, fmt, *v);
    }
}

void bar_event_cb(lv_event_t* e)
{
    lv_obj_t* bar = lv_event_get_target(e);
    lv_msg_t* m = lv_event_get_msg(e);
    const char* v = lv_msg_get_payload(m);
    lv_bar_set_value(bar, *v, LV_ANIM_OFF);
}

void charts_event_cb(lv_event_t *e) {
    lv_obj_t *obj = lv_event_get_target(e); // 获取目标对象
    if (lv_event_get_code(e) == LV_EVENT_MSG_RECEIVED) {
        lv_msg_t *msg = lv_event_get_msg(e);
        const char* v = lv_msg_get_payload(msg);
        // 根据消息类型更新对象的值
        if (msg->id == LORA_DATA_HUMI) {
            lv_chart_series_t *series = lv_chart_get_series_next(obj, NULL); // 获取图表中的下一个数据序列
            lv_chart_set_next_value(obj, series, atoi(v)); // 将新值添加到数据序列中
        } else if (msg->id == LORA_DATA_TEMP) {
            lv_chart_series_t *series = lv_chart_get_series_next(obj, NULL); // 获取图表中的下一个数据序列
            lv_chart_set_next_value(obj, series, atoi(v)); // 将新值添加到数据序列中
        } else if (msg->id == LORA_DATA_PT100) {

        }
    }
}
lv_chart_series_t *series1;
lv_chart_series_t *series2;
lv_chart_series_t *series3;
lv_chart_series_t *series4;
void inti_event(void){
    /*城市、天气、温度、时间 */
    series1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xFF0000),LV_CHART_AXIS_PRIMARY_Y);
    series2 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x00FF00),LV_CHART_AXIS_PRIMARY_Y);
    series3 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x0000FF),LV_CHART_AXIS_PRIMARY_Y);
    series4 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xFF00FF),LV_CHART_AXIS_SECONDARY_Y);
    lv_msg_subsribe_obj(WEATHER_MAIN_CITY, ui_city, "%s");
    lv_obj_add_event_cb(ui_city, label_event_cb, LV_EVENT_MSG_RECEIVED, NULL);
    lv_msg_subsribe_obj(WEATHER_MAIN_AIR, ui_tianqi, "%s");
    lv_obj_add_event_cb(ui_tianqi, label_event_cb, LV_EVENT_MSG_RECEIVED, NULL);
    lv_msg_subsribe_obj(WEATHER_MAIN_TEMP, ui_temper, "%s");
    lv_obj_add_event_cb(ui_temper, label_event_cb, LV_EVENT_MSG_RECEIVED, NULL);
    lv_msg_subsribe_obj(WEATHER_MAIN_TIME, ui_time, "%s");
    lv_obj_add_event_cb(ui_time, label_event_cb, LV_EVENT_MSG_RECEIVED, NULL);
    lv_msg_subsribe_obj(WEATHER_MAIN_DATA, ui_date, "%s");
    lv_obj_add_event_cb(ui_date, label_event_cb, LV_EVENT_MSG_RECEIVED, NULL);
    lv_msg_subsribe_obj(WEATHER_MAIN_WEEK, ui_week, "%s");
    lv_obj_add_event_cb(ui_week, label_event_cb, LV_EVENT_MSG_RECEIVED, NULL);

    //温度显示
    lv_msg_subsribe_obj(LORA_DATA_TEMP, ui_WenduLab,  "%dC");
    lv_obj_add_event_cb(ui_WenduLab, label_event_cb, LV_EVENT_MSG_RECEIVED, NULL);
    lv_msg_subsribe_obj(LORA_DATA_TEMP, ui_WenduBar, NULL);
    lv_obj_add_event_cb(ui_WenduBar, bar_event_cb, LV_EVENT_MSG_RECEIVED, NULL);
    //湿度显示
    lv_msg_subsribe_obj(LORA_DATA_HUMI, ui_HumiLab, "%d%%");
    lv_obj_add_event_cb(ui_HumiLab, label_event_cb, LV_EVENT_MSG_RECEIVED, NULL);
    lv_msg_subsribe_obj(LORA_DATA_HUMI, ui_HumiBar, NULL);
    lv_obj_add_event_cb(ui_HumiBar, bar_event_cb, LV_EVENT_MSG_RECEIVED, NULL);
    //PT100显示
    lv_msg_subsribe_obj(LORA_DATA_PT100, ui_Pt100Lab, "%dC");
    lv_obj_add_event_cb(ui_Pt100Lab, label_event_cb, LV_EVENT_MSG_RECEIVED, NULL);
    lv_msg_subsribe_obj(LORA_DATA_PT100, ui_Pt100Bar, NULL);
    lv_obj_add_event_cb(ui_Pt100Bar, bar_event_cb, LV_EVENT_MSG_RECEIVED, NULL);
    //CO显示
    lv_msg_subsribe_obj(LORA_DATA_CO, ui_CoLab, "%dppm");
    lv_obj_add_event_cb(ui_CoLab, label_event_cb, LV_EVENT_MSG_RECEIVED, NULL);
    lv_msg_subsribe_obj(LORA_DATA_CO, ui_CoBar, NULL);
    lv_obj_add_event_cb(ui_CoBar, bar_event_cb, LV_EVENT_MSG_RECEIVED, NULL);

    lv_msg_subsribe_obj(LORA_DATA_TEMP, ui_Chart1,  "%d");
    lv_msg_subsribe_obj(LORA_DATA_HUMI, ui_Chart1,  "%d");
    lv_msg_subsribe_obj(LORA_DATA_PT100, ui_Chart1,  "%d");
    lv_msg_subsribe_obj(LORA_DATA_CO, ui_Chart1,  "%d");
}