// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif
extern lv_chart_series_t *series1;
extern lv_chart_series_t *series2;
extern lv_chart_series_t *series3;
extern lv_chart_series_t *series4;
enum
{
    WEATHER_MAIN_CITY,
    WEATHER_MAIN_TEMP,
    WEATHER_MAIN_HUMI,
    WEATHER_MAIN_AIR,
    WEATHER_MAIN_TIME,
    LORA_DATA_TEMP,
    LORA_DATA_HUMI,
    LORA_DATA_PT100,
    LORA_DATA_CO,
    WEATHER_MAIN_DATA,
    WEATHER_MAIN_WEEK,
    WEATHER_MAIN_IMG,
};
void inti_event(void);
void scanWiFiNetworks(void);
void ScanAPEvent(lv_event_t * e);
void ConnetEvent(lv_event_t * e);
void EnterEvent(lv_event_t * e);
void LightPwm(lv_event_t * e);
void label_event_cb(lv_event_t* e);
void bar_event_cb(lv_event_t* e);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
