// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_DataMenu_screen_init(void)
{
    ui_DataMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DataMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WenduBar = lv_bar_create(ui_DataMenu);
    lv_bar_set_value(ui_WenduBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_WenduBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_WenduBar, 131);
    lv_obj_set_height(ui_WenduBar, 9);
    lv_obj_set_x(ui_WenduBar, -7);
    lv_obj_set_y(ui_WenduBar, -67);
    lv_obj_set_align(ui_WenduBar, LV_ALIGN_CENTER);

    ui_HumiBar = lv_bar_create(ui_DataMenu);
    lv_bar_set_value(ui_HumiBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_HumiBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_HumiBar, 142);
    lv_obj_set_height(ui_HumiBar, 10);
    lv_obj_set_x(ui_HumiBar, 84);
    lv_obj_set_y(ui_HumiBar, 97);

    ui_WenduLab = lv_label_create(ui_DataMenu);
    lv_obj_set_width(ui_WenduLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WenduLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WenduLab, 252);
    lv_obj_set_y(ui_WenduLab, 41);
    lv_obj_set_flex_flow(ui_WenduLab, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_WenduLab, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_WenduLab, "C");

    ui_HumiLab = lv_label_create(ui_DataMenu);
    lv_obj_set_width(ui_HumiLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumiLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumiLab, 252);
    lv_obj_set_y(ui_HumiLab, 93);
    lv_obj_set_flex_flow(ui_HumiLab, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_HumiLab, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_HumiLab, "%");

    ui_Pt100Lab = lv_label_create(ui_DataMenu);
    lv_obj_set_width(ui_Pt100Lab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pt100Lab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pt100Lab, 253);
    lv_obj_set_y(ui_Pt100Lab, 145);
    lv_label_set_text(ui_Pt100Lab, "C");

    ui_Pt100Bar = lv_bar_create(ui_DataMenu);
    lv_bar_set_value(ui_Pt100Bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Pt100Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Pt100Bar, 141);
    lv_obj_set_height(ui_Pt100Bar, 9);
    lv_obj_set_x(ui_Pt100Bar, 85);
    lv_obj_set_y(ui_Pt100Bar, 144);

    ui_Image1 = lv_img_create(ui_DataMenu);
    lv_img_set_src(ui_Image1, &ui_img_temperature_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image1, 17);
    lv_obj_set_y(ui_Image1, 21);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_DataMenu);
    lv_img_set_src(ui_Image4, &ui_img_humidity_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Image4, 19);
    lv_obj_set_y(ui_Image4, 76);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_DataMenu);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 107);
    lv_obj_set_y(ui_Label1, 7);
    lv_label_set_text(ui_Label1, "LORA接收");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_bold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_DataMenu);
    lv_img_set_src(ui_Image6, &ui_img_wifi_ic_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image6, 26);
    lv_obj_set_y(ui_Image6, 127);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CoBar = lv_bar_create(ui_DataMenu);
    lv_bar_set_range(ui_CoBar, 0, 150);
    lv_bar_set_value(ui_CoBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_CoBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_CoBar, 138);
    lv_obj_set_height(ui_CoBar, 10);
    lv_obj_set_x(ui_CoBar, -5);
    lv_obj_set_y(ui_CoBar, 73);
    lv_obj_set_align(ui_CoBar, LV_ALIGN_CENTER);

    ui_Image2 = lv_img_create(ui_DataMenu);
    lv_obj_set_width(ui_Image2, 10);
    lv_obj_set_height(ui_Image2, 350);
    lv_obj_set_x(ui_Image2, -28);
    lv_obj_set_y(ui_Image2, -10);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_DataMenu);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -114);
    lv_obj_set_y(ui_Label2, 75);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "CO");

    ui_CoLab = lv_label_create(ui_DataMenu);
    lv_obj_set_width(ui_CoLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CoLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CoLab, 103);
    lv_obj_set_y(ui_CoLab, 74);
    lv_obj_set_align(ui_CoLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CoLab, "ppm");

    lv_obj_add_event_cb(ui_DataMenu, ui_event_DataMenu, LV_EVENT_ALL, NULL);

}
