// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_week = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_week, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_week, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_week, -81);
    lv_obj_set_y(ui_week, 84);
    lv_obj_set_align(ui_week, LV_ALIGN_CENTER);
    lv_label_set_text(ui_week, "星期");
    lv_obj_set_style_text_color(ui_week, lv_color_hex(0x8E5168), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_week, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_week, &ui_font_bold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifibutton = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_wifibutton, 30);
    lv_obj_set_height(ui_wifibutton, 26);
    lv_obj_set_x(ui_wifibutton, 280);
    lv_obj_set_y(ui_wifibutton, 4);
    lv_obj_add_flag(ui_wifibutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifibutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifibutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifibutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_wifibutton, &ui_img_wifi_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imgbtn_create(ui_MainScreen);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_yituflow_png, NULL);
    lv_obj_set_height(ui_ImgButton2, 32);
    lv_obj_set_width(ui_ImgButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton2, 19);
    lv_obj_set_y(ui_ImgButton2, 3);

    ui_city = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_city, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_city, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_city, -97);
    lv_obj_set_y(ui_city, -50);
    lv_obj_set_align(ui_city, LV_ALIGN_CENTER);
    lv_label_set_text(ui_city, "淮南");
    lv_obj_set_style_text_color(ui_city, lv_color_hex(0x4B17D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_city, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_city, &ui_font_Black28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tianqi = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_tianqi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tianqi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tianqi, 10);
    lv_obj_set_y(ui_tianqi, -48);
    lv_obj_set_align(ui_tianqi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tianqi, "多云");
    lv_obj_set_style_text_color(ui_tianqi, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tianqi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tianqi, &ui_font_Black28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, -73);
    lv_obj_set_y(ui_time, 0);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "时间");
    lv_obj_set_style_text_font(ui_time, &ui_font_bold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temper = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_temper, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temper, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temper, 84);
    lv_obj_set_y(ui_temper, -48);
    lv_obj_set_align(ui_temper, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temper, "32");
    lv_obj_set_style_text_color(ui_temper, lv_color_hex(0xFA6C09), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temper, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temper, &ui_font_Black28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, -77);
    lv_obj_set_y(ui_date, 41);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "日期");
    lv_obj_set_style_text_font(ui_date, &ui_font_bold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_wifibutton, ui_event_wifibutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);

}
