// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Other_screen_init(void)
{
    ui_Other = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Other, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Other);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 110);
    lv_obj_set_y(ui_Label4, 49);
    lv_label_set_text(ui_Label4, "亮度调节");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_bold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Other);
    lv_slider_set_value(ui_Slider1, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 212);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 66);
    lv_obj_set_y(ui_Slider1, 127);


    ui_Label5 = lv_label_create(ui_Other);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 129);
    lv_obj_set_y(ui_Label5, 175);
    lv_label_set_text(ui_Label5, "50%");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Black28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Other, ui_event_Other, LV_EVENT_ALL, NULL);

}
