// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Wifi_screen_init(void)
{
    ui_Wifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_Wifi);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 112);
    lv_obj_set_y(ui_Switch1, -88);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_Dropdown1 = lv_dropdown_create(ui_Wifi);
    lv_dropdown_set_options(ui_Dropdown1, "KK\nMERCURY_1D6622");
    lv_obj_set_width(ui_Dropdown1, 219);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 6);
    lv_obj_set_y(ui_Dropdown1, 12);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Keyboard1 = lv_keyboard_create(ui_Wifi);
    lv_obj_set_width(ui_Keyboard1, 314);
    lv_obj_set_height(ui_Keyboard1, 134);
    lv_obj_set_x(ui_Keyboard1, -1);
    lv_obj_set_y(ui_Keyboard1, 137);

    ui_TextArea1 = lv_textarea_create(ui_Wifi);
    lv_obj_set_width(ui_TextArea1, 308);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_x(ui_TextArea1, 7);
    lv_obj_set_y(ui_TextArea1, 57);
    lv_textarea_set_placeholder_text(ui_TextArea1, "PASSWORD");
    lv_textarea_set_one_line(ui_TextArea1, true);
    lv_textarea_set_password_mode(ui_TextArea1, true);



    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wifi, ui_event_Wifi, LV_EVENT_ALL, NULL);

}
